### ISSUE TITLE
Megaman 64 barrier

### ISSUE THREAD

**Issue by Themaister** [Themaister/parallel-rdp#1]
After Tutorial zone.
![Mega_Man_64_USA-200517-110941](https://user-images.githubusercontent.com/163683/82140817-c8ecc100-9831-11ea-828f-f6768970b506.png)

**Comment by OtavioRaposo** [comment]
The enemies explosions (when they die) are also missing.

**Comment by Themaister** [comment]
Fixed by https://github.com/Themaister/parallel-rdp/commit/ef1d7b801397b1291896d7b4f7f09e41349a19c7
