### ISSUE TITLE
Texture filtering options (tentative request)

### ISSUE THREAD

**Issue by DerKoun** [Themaister/parallel-rdp#12]
I know this is not easy, as the renderer does not use high-level 3D functionality (of course feel free to correct me if I'm wrong). I'm wondering if, in addition to higher resolutions, other improvements would be feasible. I think one that would further enhance the image well would be texture filtering options. So one could switch from the N64-specific filtering to normal bilinear, trilinear or even anisotropic (I'd love the latter, but assume it would be complex).

**Comment by Themaister** [comment]
paraLLEl-RDP targets accuracy, and this feature intentionally does things in a way that does not reflect the hardware. Software rendering makes anisotropic basically impossible.

**Comment by DerKoun** [comment]
OK, had to try :)
Good look with the project
