### ISSUE TITLE
Overscan option cropping 2px vertically for only 1px horizontally?

### ISSUE THREAD

**Issue by bslenul** [Themaister/parallel-rdp#13]
Hey, m4xw told me on Discord it would be a parallel-rdp issue so I guess I'm in the right place?

With either ParaLLEl or Mupen64Plus-Next core on RetroArch, with ParaLLEl-RDP the overscan option stretches the image vertically.

It's not super obvious on low values but it's definitely there, it's like for 2px vertically, it's only doing it for 1px horizontally. 

Banjo-Kazooie with the option set to "14":

![banjo](https://user-images.githubusercontent.com/33353403/86461990-24fc9d80-bd2b-11ea-8104-4084e310a86f.gif)

And for something really obvious, Super Mario 64 with the option set to "64":

![mario](https://user-images.githubusercontent.com/33353403/86456240-1067d780-bd22-11ea-9957-8fdb8862eb4a.gif)

**edit:** Another comparison with 640x480 screenshots, with overscan set at "0":

![Banjo-Kazooie (USA)-200703-133641](https://user-images.githubusercontent.com/33353403/86466076-482b4b00-bd33-11ea-9b5e-8ef5ba3cdf6d.png)

And "4":

![Banjo-Kazooie (USA)-200703-133657](https://user-images.githubusercontent.com/33353403/86466091-50838600-bd33-11ea-84c1-c56da52fd27f.png)

So yeah, looks like it crops properly 4px on the left and right, however it crops 8px on top and bottom.

**Comment by Themaister** [comment]
Fixed by https://github.com/Themaister/parallel-rdp/commit/fe30be669522aa0d9e6d32846f721c1bc5636270

**Comment by bslenul** [comment]
Awesome, thank you! 👍
