### ISSUE TITLE
Naboo glitching

### ISSUE THREAD

**Issue by Themaister** [Themaister/parallel-rdp#2]
Some vague glitching in first missing with textures, but needs to be verified.

**Comment by OtavioRaposo** [comment]
It's not a glitch. It's just that the interlacing is very strong and noticiable. It would be good if could disable interlacing and enable overscan at the same time.

**Comment by Themaister** [comment]
It's not interlacing, large swathes of geometry pop in and out in a glitchy way, but it seems to happen exactly same way on AL, so might be a core issue with parallel-n64. I ran dump validation and it passes bitexact for me with AL, so going to call it fine from parallel POV.

FWIW, it's possible to disable VI interlacing.
