### ISSUE TITLE
Individual Overscan function for ParaLLEl-RDP

### ISSUE THREAD

**Issue by Turaltay** [Themaister/parallel-rdp#28]
The performance of the ParaLLEl-RDP is great but there is one little detail that would make it perfect for me. Is it possible to add a overscan crop function that can be used to adjust the left, right, top and bottom of the image individually (like in GlideN64)? 
![Unbenannt](https://user-images.githubusercontent.com/39458480/127205731-f250a31f-1c53-4357-a031-7552cb0b5c37.png)
The current overscan function only allows to crop the complete picture. Unfortunately, this always cuts off parts of the game screen too.

**Comment by Themaister** [comment]
Added support for this on master.
