### ISSUE TITLE
DX11 for non-Vulkan GPUs

### ISSUE THREAD

**Issue by ToruTheRedFox** [Themaister/parallel-rdp#33]
DX11 also supports compute shaders and has much wider GPU compatibility, plus on a lot of GPUs is faster than any other graphics API (due to lazy implementations, some companies were too lazy to even implement Vulkan at all for a long time) so I guess it makes sense, especially for systems that'd benefit the most from the speed boost (like my mid-2012 MacBook Pro lol)

**Comment by Themaister** [comment]
DX11 is far from capable enough.

**Comment by ToruTheRedFox** [comment]
huh

sucks that Vulkan support is so spotty
