### ISSUE TITLE
Assistance with native Vulkan rendering in m64p

### ISSUE THREAD

**Issue by loganmc10** [Themaister/parallel-rdp#36]
As you may be aware, parallel-rdp was ported to mupen64plus. However, the implementation isn't pure Vulkan. The image is copied to memory and then rendered using OpenGL since the mupen64plus API only supports OpenGL. See https://github.com/loganmc10/m64p/blob/main/parallel-rdp-standalone/parallel_imp.cpp#L40-L76

I'm trying to fix things up so it also draws the image using Vulkan. See the work here: https://github.com/loganmc10/m64p/tree/vk

Here is the workflow:
- Qt creates a QWindow and sets the surfaceType to VulkanSurface (https://github.com/loganmc10/m64p/commit/d1b117c59fbb50c2fa68935f5d9bf1148b896d02#diff-f040c60f8b334abe1be59cefcd0867434948e077d65f20e27e8663a138f7670fR12)
- parallel-rdp creates the Vulkan device and instance, then the instance is passed to Qt and assigned to the QWindow. https://github.com/loganmc10/m64p/commit/d1b117c59fbb50c2fa68935f5d9bf1148b896d02#diff-bf9fae697a8b60e7a2ba81afeb539afeb67c37ede47fb3c82321327365f422f1R228-R230 

This all works, the emulator runs, doesn't crash, and the audio plays in the background.

However, I don't know anything really about Vulkan. I'm not sure exactly what to do to take the image and render it on the window (how to replace https://github.com/loganmc10/m64p/blob/main/parallel-rdp-standalone/parallel_imp.cpp#L40-L76 basically).

Any tips/guidance/assistance you could offer would be greatly appreciated.

**Comment by loganmc10** [comment]
@mudlord if you're interested, I know you did the original port to OpenGL. I'd really like to figure out how to get pure vulkan rendering going, but I'm unclear on the process to draw something on to the frame buffer

**Comment by philou-felin** [comment]
As an end-user, I would definitely like to see your work in more emulators.

**Comment by mudlord** [comment]
As far as I know with parallel-rdp it gives a [Vulkan texture handle](https://github.com/Themaister/parallel-rdp/blob/b355d60aa32c8647670634d30ea1b107c3f78b05/parallel-rdp/video_interface.hpp). From there, its left up to you to set up the render context, and drawing the texture. This has to be done with a shader, which is converted from GLSL to SPIRV using one of the many shader compilers around.

[This might be of some guidance](https://github.com/Dillonb/n64/blob/fc851e5f548a622df0eb9a46a9eaf8d3f878c6e7/src/rdp/parallel_rdp_wrapper.cppl)
