### ISSUE TITLE
Bottom of the 9th - blue tint

### ISSUE THREAD

**Issue by loganmc10** [Themaister/parallel-rdp#37]
See: https://github.com/mupen64plus/mupen64plus-core/issues/928
![image](https://user-images.githubusercontent.com/848146/153766081-05c1403e-bec8-46d6-8797-00962081f5e9.png)

Should look like this:
![image](https://user-images.githubusercontent.com/848146/153766095-00d102c3-c63b-4771-bdfe-3c0c9b6c5431.png)

**Comment by Meerkov** [comment]
On closer examination, it looks like the color channels are messed up.
green => blue
Red => Green
Blue => red

Some kind of "off by one" error in the header for the file?

**Comment by Jj0YzL5nvJ** [comment]
[Intel graphics?](https://github.com/ata4/angrylion-rdp-plus/issues/77)

**Comment by loganmc10** [comment]
It only happens on this game, so I don't think so, I believe that bug would express itself in every game

**Comment by Themaister** [comment]
YUV shenanigans. Need to refactor that entire mess ....

**Comment by Themaister** [comment]
Fixed on master.
