### ISSUE TITLE
Infernal Machine fails to load out of first level

### ISSUE THREAD

**Issue by plexecutor** [Themaister/parallel-rdp#4]
Upon completing the Canyon level, the game fails to load out of the level and just sits indefinitely at a black screen. I can reproduce this every time. I confirmed it works fine (albeit slowly) using angrylion/cxd4 instead of parrallel/parrallel for the GFX and RDP plugins

**Comment by Themaister** [comment]
Unlikely to be an RDP bug. More likely to be RSP, which means it does not belong here. Did you try Angrylion with cxd4/parallel-rsp?

**Comment by OtavioRaposo** [comment]
I can confirm this, but the screen doesn't stay black indefinitely.
After some long time the level is loaded.
It happens in angrylion/parallel.

**Comment by Themaister** [comment]
Ok, doesn't sound like an RDP bug there, please file the issue on the relevant repo for the emulator, I'm going to assume parallel-n64 was used here.
