### ISSUE TITLE
Garbled mess of colors using Vulkan on m64p/Ares. 

### ISSUE THREAD

**Issue by mysterystain** [Themaister/parallel-rdp#45]
I was told I should open an issue here just in case it may be relevant. 
https://github.com/ares-emulator/ares/issues/634
Link contains all original information along with screenshots. Wasn't sure if it was appropriate to copy and paste everything so I opted to include a link instead. 

It involves a problem from above. I've tried testing some more and it does look like Ares did not cause it though we already suspected such. The only other change I can recall is when Fallout76 had to be migrated from the bethesda launcher over to steam. 

I tried using only m64p to confirm whether or not Ares had any impact and it eventually started anyway. Though on a more recent occasion, it then began immediately upon attempting to use Ares. 

In the past, I have used rcps3 and cemu. The most recent usage was testing dead space on rpcs3. I was checking to see if audio was okay and only played around for a few minutes. I don't recall when I did that but it was some time before this whole thing started.

**Comment by mysterystain** [comment]
Update: For the second time in a row, the garbled mess of colors began immediately after trying to load an N64 game on Ares when it was previously working fine on m64p. The time it took for the issue to re-occur was much faster than usual.

**Comment by mysterystain** [comment]
Seems to happen to all vulkan-based usages. Updates haven't worked. Must be my machine. No idea why still though.

**Comment by Squall-Leonhart** [comment]
This is an nvidia driver issue where when the available video memory reaches critical levels and the applications initial allocation exceeds that level, texture and colour mapping are broken.

In some scenario's this can even crash the video driver.

**Comment by mysterystain** [comment]
Thanks for this info! It's good to finally know what is the problem. Would you happen to know any possible fixes?

**Comment by Squall-Leonhart** [comment]
Check with processhacker (not processexplorer or task manager) to identify any shell processes consuming lots of VRAM, usually this will be Explorer.exe on Windows 10 (particularly if >100% dpi is used).  Kill any processes that are.

on Turing hardware and later, there is a pageable memory extension available that can mitigate this issue to an extent, but must be utilised in the vulkan render code.

**Comment by mysterystain** [comment]
Thank you for the information. I've been playing a lot, waiting until it happened again so I could try this fix but it's not doing it anymore. I hadn't played either of these emulators in over a year and maybe it fixed itself or I'm doing something different that isn't allowing it to happen now. Either way, I'm still very grateful for your assistance and I will hold onto this for the future in case this ugly issue rears its head again.
