### ISSUE TITLE
Indiana Jones Indy's Trading Post

### ISSUE THREAD

**Issue by OtavioRaposo** [Themaister/parallel-rdp#7]
Every time you finish a level in Indiana Jones, you go to a scene called Indy's Trading Post to spend your treasures. But most of the times the game keeps freezing in this scene or is unplayable slow. It works ok in HLE emulation.

**Comment by Themaister** [comment]
This is not an actionable report. This could very well be caused by parallel-n64 or parallel-rsp.

**Comment by plexecutor** [comment]
Themaister, I submitted this same bug a few days ago but you closed the report. I can confirm that it happens only when using parallel-rdp. Any combination of parallel-rdp with hle/cxd4/parallel RSP results in this error. Works when using any other RDP plugin with any RSP plugin. I am happy to help you diagnose this or rule things out. Just let us know what you need.

**Comment by OtavioRaposo** [comment]
Now, I tried this scene again using both parallel-rsp and parallel-rdp. The scene is loading, but the graphics are not rendering correctly.
![image](https://user-images.githubusercontent.com/36393971/83301133-7adfa200-a1cf-11ea-848d-779415cfa422.png)
