### ISSUE TITLE
Deinterlacing

### ISSUE THREAD

**Issue by damianshrinivas** [Themaister/parallel-rdp#9]
Hi, can you implement some kind of deinterlacing in high resolution modes (Turok 2 for an example)? Cause now it is only screen shaking (interlacing off) or black stripes everywhere (interlacing on).

**Comment by plexecutor** [comment]
Second this. Something really wonky is going on with interlaced games right now. CRT-Royale actually caused some severe image retention on my LCD screen when playing Indiana Jones for about a half hour due to the weird interlacing artifacts mixed with the shader. Thankfully it went away on its own.

**Comment by Themaister** [comment]
The current deinterlacing methods are the lame alternatives "bob" or "weave".
Black stripes everywhere is kinda surprising though, that shouldn't happen. Do you have screenshots?

**Comment by damianshrinivas** [comment]
I mean this, it happens with movement![Castlevania - Legacy of Darkness (USA)-200526-202216](https://user-images.githubusercontent.com/19475260/82936428-df5fee80-9f8e-11ea-9959-58122b28b1d8.png)

**Comment by Themaister** [comment]
Yes, these are classic weave interlacing artifacts that AL implements, I have plans to make a "better" deinterlacer eventually.

**Comment by OtavioRaposo** [comment]
Sorry for the flood, but I've to third this.
Interlacing is many times strongly noticeable.
I'll just give one indisputable example: Battle for Naboo opening animation.

**Comment by Themaister** [comment]
A new reasonably simple deinterlacer is implemented. The typical bob or weave artifacts are gone.
